### ISSUE TITLE
Typescript Research

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-sdk-cpp#32]
- What typescript->WASM compilers exist?
   - How easily can you retarget the compiled WASM? (i.e. Javascript bindings in a browser)
   - How mature is the compiler and does it have an active developer base?
   - What set of language features are targeted and do we need non-targeted features? (i.e. C++ exceptions do not work for clang WASM, but are not needed)

- We aren't Typescript devs and need a language overview to understand what features are important to Typescript devs. (Are those included in the subset above?)

- How large are the output WASM binaries? Compare simple C++ and Typescript contracts that do and do not use standard libraries.

**Comment by sgerbino** [comment]
I think we can close this due to the great work of @roaminroe at this repository: https://github.com/roaminroe/koinos-as-sdk
